#!/bin/sh

rm test.md intermediate.html

node src/index.js

pandoc \
  -t html \
  $1 \
  -H src/assets/template.html \
  -o intermediate.html

# wkhtmltopdf \
#   -d 300 -L 12.7 -R 12.7 -T 12.7 -B 12.7 \
#   --enable-internal-links \
#   --footer-html src/assets/footer.html \
#   --page-width 152mm \
#   --page-height 228mm \
#   intermediate.html output.pdf

node htmlpdf.js
